authapp/urls.py
from django.urls import path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
]

cip_bmstu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('mainapp.urls')),
    path('authapp/', include('authapp.urls')),
    path('mainapp/',include('mainapp.urls')),
    path("", include('documentapp.urls'))
]

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    username = models.CharField(max_length=15, unique=False)
    email = models.EmailField(max_length=100, unique=True)

authapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import CustomUser

class CreateUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password1', 'password2']

authapp/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib import messages
from .forms import CreateUserForm
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from .tokens import account_activation_token
import os
import re

def validate_email(email):
    pattern = r'^[a-zA-Z0-9._%+-]+@.*bmstu\.ru$'
    return re.match(pattern, email) is not None

def login_view(request: HttpRequest):
    if request.method == "GET":
        if request.user.is_authenticated:
            messages.success(request, 'Вы уже в системе.')
            return redirect('/')
        return render(request, 'authapp/login.html')
    email = request.POST["email"]
    password = request.POST["password"]
    user = authenticate(request, username=email, password=password)
    if user:
        if user.is_active:
            login(request, user)
            messages.success(request, 'Вы успешно вошли.')
            return redirect('/')
        else:
            messages.error(request, 'Подтвердите свою элетронную почту.')
            return redirect('/')
    else:
        return render(request, "authapp/login.html", {"error": "Invalid login credentials"})

def logout_view(request: HttpRequest):
    logout(request)
    return redirect('/')

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Ваша почта подтверждена.")
        return redirect('/authapp/login')
    else:
        messages.error(request, "Ссылка недействительна.")
    return redirect('/')

def activate_email(request, user, to_email):
    mail_subject = "Центр Интеллектуальной Собственности МГТУ им. Н.Э. Баумана"
    message = render_to_string("authapp/activate_account.html", {
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Письмо с подтверждением почты отправлено на адрес <b>{to_email}</b>.')
    else:
        messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')

def signup_view(request: HttpRequest):
    if request.method == "GET":
        if request.user.is_authenticated:
            messages.success(request, 'Вы уже в системе.')
            return redirect('/') 
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if validate_email(email):             
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                activate_email(request, user, email)
                return redirect('/')
            else:
                form.add_error('email', 'Используйте электронную почту с доменом bmstu')
    context = {'form': form}
    return render(request, 'authapp/signup.html', context)

authapp/templates/authapp/activate_account.html
{% autoescape off %}
Здравствуйте.

Пожалуйста, перейдите по ссылке ниже, чтобы подтвердить свою регистрацию на портале:

{{ protocol }}://{{ domain }}{% url 'authapp:activate' uidb64=uid token=token %}
{% endautoescape %}

authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title %}
    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block title %}
    Вход
{% endblock%}

{% block body %}
<div class="row">
  <div class="container col-md-3 text-center">  
    <form method="POST">
      {% csrf_token %}

      <img class="mb-4" width="125" height="125" src="{% static 'mainapp/image/bmstu.png' %}" alt="BMSTU">
      <h1 class="h3 mb-3 fw-normal">Вход</h1>

      <div class="form-floating mb-3">
        <input type="email" class="form-control" id="email" name="email" placeholder="name@bmstu.ru">
      </div>

      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password" name="password" placeholder="Пароль">
      </div>

      <div class="checkbox mb-2">
        <label>
          <input type="checkbox" value="remember-me"> Запомнить меня
        </label>
      </div>
      
      <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
    </form>
    <p class="mt-2"><a target="_blank" href="/authapp/signup" class="text-dark">Зарегестрироваться<img width="16" height="16" src="{% static 'mainapp/image/arrow-up-right.svg' %}" alt="arrow"></a></p>
  </div>
</div>

{% endblock %}

authapp/templates/authapp/signup.html
{% extends 'authapp/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Регистрация
{% endblock%}

{% block body %}
<div class="row">  
  <div class="container col-md-3 text-center">
    <form method="POST">
      {% csrf_token %}

      <img class="mb-4" width="125" height="125" src="{% static 'mainapp/image/bmstu.png' %}" alt="BMSTU">
      <h1 class="h3 mb-3 fw-normal">Регистрация</h1>

      <div class="form-floating mb-3">
        {% comment %} <input type="email" class="form-control" id="email" placeholder="name@bmstu.ru"> {% endcomment %}
        {% render_field form.email type="email" class="form-control" id="id_email" placeholder="name@bmstu.ru"%}
      </div>

      <div class="form-floating mb-3">
        {% comment %} <input type="password" class="form-control" id="password" placeholder="Пароль"> {% endcomment %}
        {% render_field form.password1 type="password" class="form-control" id="password" placeholder="Пароль"%}
      </div>

      <div class="form-floating mb-3">
        {% comment %} <input type="password" class="form-control" id="password_confirmation" placeholder="Подтверждение пароля"> {% endcomment %}
        {% render_field form.password2  type="password" class="form-control" id="password_confirmation" placeholder="Подтверждение пароля"%}
      </div>

      <div class="form-floating mb-3">
        <input type="text" class="form-control" name="secret_key" id="secret_key" placeholder="Секретный ключ">
      </div>

      <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегестрироваться</button>
      </form>
      {{ form.errors }}
  </div>
</div>
{% endblock %}